### ISSUE TITLE
Exception thrown while generating bindings

### ISSUE THREAD

**Issue by frabert** [luca-piccioni/OpenGL.Net#48]
I've been recently trying to generate bindings without success, as BindingsGen tries to load DTDs from the wrong paths apparently:

`````
System.IO.FileNotFoundException occurred
  HResult=0x80070002
  Message=Impossibile trovare il file 'D:\Documenti\GitHub\OpenGL.Net\RefPages\EN'.
  Source=mscorlib
  StackTrace:
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at BindingsGen.RegistryDocumentationHandler.LocalXhtmlXmlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn) in D:\Documenti\GitHub\OpenGL.Net\BindingsGen\RegistryDocumentationHandler.cs:line 358
   at System.Xml.XmlTextReaderImpl.OpenAndPush(Uri uri)
   at System.Xml.XmlTextReaderImpl.PushExternalEntityOrSubset(String publicId, String systemId, Uri baseUri, String entityName)
````

The DTD in question is `{file:///D:/Documenti/GitHub/OpenGL.Net/BindingsGen/bin/Debug/-/OASIS/DTD DocBook V4.2/EN}` according to the debugger.

**Comment by frabert** [comment]
I have worked around the problem by editing the offending line:
`````diff
- return (new FileStream(Path.Combine(DocumentPath, localPath), FileMode.Open, FileAccess.Read));
+ return null;
`````

**Comment by luca-piccioni** [comment]
Just cloned and run BindingsGen in _Release_ and _Debug_. Everything is fine on my machine (TM).

The patch won't prevent the documentation generation? Alternatively, you can get rid of GL2 and GLES1 reference pages: it will improve memory footprint and performance.

Still wonder why your instance is failing. Are you sure to be in sync with master/head? I've already seen that exception in the past.

**Comment by frabert** [comment]
I have just deleted my local repository and starting from scratch to eliminate all possible factors. Anyway, I saw quite a large consumption of memory while generating the bindings (> 4GB), it went down to about 200MB after bypassing the whole `GetEntity` method). What is this method supposed to do? I could only understand that it obtains the DTDs necessary for validation of the XMLs' file schemas, but I might be mistaken...

**Comment by luca-piccioni** [comment]
GL2 and GLES1 reference pages have MathML (mml) namespaces that are not recognized if DTD parsing is not enabled. If you find a way to load documentation without DTD processing you'll make me a big favor (it consume so much memory).

Everything can be optimized, since the GL2 and GLES1 XML documents are cached (infact they are occupying all that memory): it will be sufficient to cache only the required documentation.

About `GetEntity`... I don't remember exactly, but essentially allows DTD processing from XmlDocument, using local DTDs. If you disable it (by returning null), no XML documentation is loaded.

**Comment by frabert** [comment]
The exception remains, unfortunately...
Anyway, I will just disable the entity management for now since I do not need the docs to test the thing I am working on. I have found this though: [AngleSharp](https://anglesharp.github.io/). It looks like it may do the trick, since it supports XML loading without validation. I will look into it when I am done the other thing I am working on.
